import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { ThemeProvider } from "@/app/appcomponents/theme-provider";
import Navbr from "../appcomponents/Navbr";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  
}: {
  children: React.ReactNode;
  
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbr />
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </ThemeProvider>
         
        </body>
      </html>
    </ClerkProvider>
  );
}
export const runtime = 'edge'